services:

  db:
    build:
      context: .
      dockerfile: Dockerfile.db
    image: faysk/whatsapp-db:latest
    container_name: whatsapp-db
    env_file:
      - .env
    restart: unless-stopped
    environment:
      TZ: America/Sao_Paulo
    volumes:
      - db_data:/var/lib/postgresql/data:rw
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB} -h localhost -q"]
      interval: 10s
      timeout: 5s
      start_period: 20s
      retries: 5
    dns:
      - 1.1.1.1
      - 8.8.8.8
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"
    networks:
      - backend

  bot:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        GO_ENV: production
    image: faysk/whatsapp-bot:latest
    container_name: whatsapp-bot
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    restart: on-failure:5
    environment:
      TZ: America/Sao_Paulo
      DATABASE_DSN: ${DATABASE_DSN}
      PORT: ${PORT}
      HTTP_HEALTH_ENDPOINT: ${HTTP_HEALTH_ENDPOINT:-/health}
    tmpfs:
      - /tmp
    dns:
      - 1.1.1.1
      - 8.8.8.8
    healthcheck:
      test: ["CMD-SHELL", "curl -sf http://localhost:${PORT}${HTTP_HEALTH_ENDPOINT:-/health} || exit 1"]
      interval: 20s
      timeout: 5s
      start_period: 40s
      retries: 3
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"
    networks:
      - backend

volumes:
  db_data:

networks:
  backend:
    driver: bridge
